# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/task_176313218821961/pip-feedstock/recipe, last modified Fri Nov 14 14:56:48 2025
# ------------------------------------------------

package:
  name: pip
  version: '25.3'
source:
  sha256: 8d0538dbbd7babbd207f261ed969c65de439f6bc9e5dbd3b3b9a77f25d95f343
  url: https://pypi.org/packages/source/p/pip/pip-25.3.tar.gz
build:
  disable_pip: true
  entry_points:
    - pip = pip._internal.cli.main:main
    - pip3 = pip._internal.cli.main:main
  noarch: python
  number: '0'
  string: pyhc872135_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 51_gnu
    - bzip2 1.0.8 h998d150_6
    - ca-certificates 2025.11.4 hd43f75c_0
    - expat 2.7.3 hc366171_0
    - flit-core 3.12.0 py313h36db77b_1
    - ld_impl_linux-aarch64 2.44 h4e4ac68_2
    - libffi 3.4.4 h419075a_1
    - libgcc 15.2.0 hc18542e_7
    - libgcc-ng 15.2.0 h51576c1_7
    - libgomp 15.2.0 hf47c802_7
    - libmpdec 4.0.0 h998d150_0
    - libstdcxx 15.2.0 h9538471_7
    - libstdcxx-ng 15.2.0 h719ae8e_7
    - libuuid 1.41.5 h998d150_0
    - libxcb 1.17.0 hf66535e_0
    - libzlib 1.3.1 h998d150_0
    - ncurses 6.5 h419075a_0
    - openssl 3.0.18 h8a9c3cf_0
    - pthread-stubs 0.3 hfd63f10_1
    - python 3.13.9 h572d80e_100_cp313
    - python_abi 3.13 1_cp313
    - readline 8.3 h886d1d0_0
    - sqlite 3.51.0 hc5b20ee_0
    - tk 8.6.15 h987d8db_0
    - tzdata 2025b h04d1e81_0
    - xorg-libx11 1.8.12 hf66535e_1
    - xorg-libxau 1.0.12 hf66535e_0
    - xorg-libxdmcp 1.1.5 hf66535e_0
    - xorg-xorgproto 2024.1 h998d150_1
    - xz 5.6.4 h998d150_1
    - zlib 1.3.1 h998d150_0
  run:
    - python >=3.9,<3.14.0a0
    - setuptools
    - wheel
test:
  commands:
    - pip -h
    - pip list
  imports:
    - pip
  requires:
    - python 3.9.*
about:
  description: 'pip is the package installer for Python.

    You can use pip to install packages from the Python Package

    Index and other indexes.

    '
  dev_url: https://github.com/pypa/pip
  doc_url: https://pip.pypa.io
  home: https://pip.pypa.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PyPA recommended tool for installing Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
  skip-lints:
    - missing_pip_check
    - python_build_tool_in_run
    - python_build_tools_in_host
