# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /Users/ec2-user/tasks/task_175948879437352/openssl-feedstock/recipe, last modified Fri Oct  3 10:55:34 2025
# ------------------------------------------------

package:
  name: openssl
  version: 3.0.18
source:
  sha256: d80c34f5cf902dccf1f1b5df5ebb86d0392e37049e5d73df1b3abae72e4ffe8b
  url: https://github.com/openssl/openssl/releases/download/openssl-3.0.18/openssl-3.0.18.tar.gz
build:
  binary_has_prefix_files:
    - lib/libcrypto.3.0.dylib
    - lib/libcrypto.a
  detect_binary_files_with_prefix: true
  has_prefix_files:
    - bin/c_rehash
    - lib/pkgconfig/libcrypto.pc
    - lib/pkgconfig/libssl.pc
    - lib/pkgconfig/openssl.pc
  no_link: lib/libcrypto.3.0.dylib
  number: '0'
  run_exports:
    - openssl >=3.0.18,<4.0a0
  string: h9b4081a_0
requirements:
  build:
    - cctools 986 h0dbccd1_3
    - clang 17.0.6 hdefe189_6
    - clang-17 17.0.6 default_h000693a_6
    - clang_impl_osx-arm64 17.0.6 hcb56dc5_4
    - clang_osx-arm64 17.0.6 hcb56dc5_4
    - clangxx 17.0.6 default_h000693a_6
    - compiler-rt 17.0.6 h6a6761b_1
    - compiler-rt_osx-arm64 17.0.6 h6a6761b_1
    - icu 73.1 h313beb8_0
    - ld64 711 h3c27c41_3
    - libclang-cpp17 17.0.6 default_h000693a_6
    - libcxx 17.0.6 he5c5206_4
    - libcxx-devel 17.0.6 hbf97328_4
    - libffi 3.4.4 hca03da5_1
    - libiconv 1.16 h80987f9_3
    - libllvm17 17.0.6 h07a7f36_6
    - libxml2 2.13.8 h0b34f26_0
    - llvm 17.0.6 h0bf6939_6
    - llvm-tools 17.0.6 hcb83754_6
    - lz4-c 1.9.4 h313beb8_1
    - macosx_deployment_target_osx-arm64 12.1 h1c4a9a5_1
    - make 4.3 h620ffc9_1
    - perl 5.38.2 0_h80987f9_perl5
    - tapi 1100.0.11 h8754e6a_1
    - xz 5.6.4 h80987f9_1
    - zlib 1.2.13 ha1e9f54_2
    - zstd 1.5.6 hfb09047_0
  host:
    - __osx >=12.1
  run:
    - __osx >=12.1
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - openssl sha256 checksum.txt
    - openssl ecparam -name prime256v1
    - python -c "import urllib.request; urllib.request.urlopen('https://pypi.org')"
    - pkg-config --print-errors --exact-version "3.0.18" openssl
  requires:
    - pkg-config
    - python 3.9.*
about:
  description: 'OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit

    for the Transport Layer Security (TLS) protocol formerly known as the

    Secure Sockets Layer (SSL) protocol. The protocol implementation is based

    on a full-strength general purpose cryptographic library, which can also

    be used stand-alone.

    '
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: https://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - chenghlee
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
